# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV["VAGRANT_EXPERIMENTAL"] = "disks"
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.box = "ubuntu/focal64"
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
    vb.vm.box = "ubuntu/focal64"
    
    config.vm.disk :disk, size: "300MB", name: "drive_1"
    config.vm.disk :disk, size: "300MB", name: "drive_2"
    config.vm.disk :disk, size: "300MB", name: "drive_3"
    config.vm.disk :disk, size: "300MB", name: "drive_4"
  

    config.vm.provision "shell", path: "storage.sh"

  end


end